# Marty Dang 3/13/18

# This program does the followering:
# 1. Takes in an input of a .txt file, as command prompt
# 2. It then scans and picks out the individual words
# 3. Outputs those words to another file
# 4. In that other file, it should append the link of the website with the word
# 5. Append all of that to a href tag for html

#Be sure to have your input text file in the same location as this program!

# Read/Open the file, outputs a list of lists 
def processFile():

	clean_file = []

	file = input("Please enter in your file: ")

	with open(file) as f:

		for read_data in f:
			#read_data = f.readline() #read in lines as strings
			read_data = read_data.split() #gets rid of spaces, tab chars etc
			read_data = read_data[2:] #gets rid of first two numbesr
			clean_file.append(read_data) #Add to list 
	f.closed

	return clean_file
################################################################################

#Will create a file with just key words and link them 
def createNewFile(inputFile):

	counter = 0 
	f = open('generatedFile.html','w') #create another file
	f.write('<!-- Code generated by Marty Dang-->' + '\n')

	#Add in the standard HTMl stuff
	# <!DOCTYPE html> 
    # <html lang="en">
    # <body> 
	f.write('<!DOCTYPE html>' + '\n')
	f.write('<html lang=' + '"en"'+ '>' + '\n' +'\n' )
	f.write('  ' + '<body>' + '\n')
	f.write( '  ' + '<center><h2>Dummy Navigator</h2></center>' + '\n' +'\n')

	#loop through and find words 
	for topic in inputFile:
		f.write('  ' + '<h3>' + "Topic " + str(counter) + '</h3>' + '\n' + '\n')
		counter+=1 # to keep track of topic number

		for word in range(len(topic)):

			# This is the hardcoded link for the site we are using. 
			# So if you wanted to use a diff. link, replace this part

			f.write('  ' + '<a href=' +
				'"' + 'https://digitalricoeur.org/about;((%22c%22%20.%20%220sGYqH%2FbjxS96qpeU ' + '\n' + ' ' + 
				' 9ItA68y67jcoKDMpIDMgKCgobGliICJ3ZWItc2VydmVyL2xhbmcvYWJvcnQtcmVzdW1lLnJrdCIpIC4g ' + '\n' + ' ' +
	            ' ImxpZnRlZC4zIikgKChsaWIgIndlYi1zZXJ2ZXIvbGFuZy93ZWItY2VsbHMucmt0IikgLiBkZXNlcmlh ' + '\n' + ' ' +
	            ' bGl6ZS1pbmZvOmZyYW1lLXYwKSAoKGxpYiAicmljb2V1ci9wb3J0YWwvdGVybS1zZWFyY2gucmt0Iikg ' + '\n' + ' ' +
	            ' LiAibGlmdGVkLjQ3NDUiKSkgMCAoKSAoKSAoMCAoMSAoaCAtICgpIChsaWZ0ZWQuNTQtMCB1IC4gImh0 ' + '\n' + ' ' +
	            ' dHBzOi8vZGlnaXRhbHJpY29ldXIub3JnLyIpIChsaWZ0ZWQuMjQ0MC04IC4gI2YpIChsaWZ0ZWQuMjQw ' + '\n' + ' ' +
	            ' NC02IC4gI3QpIChsaWZ0ZWQuMTIwMDYtMiAuIGxhdGVzdC10by1vbGRlc3QpIChsaWZ0ZWQuMTIwMjQt ' + '\n' + ' ' +
	            ' MyAuIGxhdGVzdC10by1vbGRlc3QpIChsaWZ0ZWQuMTU4NS00IC4gdGVtcDE1KSAobGlmdGVkLjIzODYt ' + '\n' + ' ' +
	            ' NSAuIGZpcnN0LT5sYXN0KSAobGlmdGVkLjI0NTgtOSAuIGFueSkgKGxpZnRlZC4yNDIyLTcgLiAjdCkg ' + '\n' + ' ' +
	            ' KGxpZnRlZC4xMTk4OC0xIC4gbGFzdC11c2VkKSAobGlmdGVkLjEwMzgtMTAgLiB0ZW1wMSkpKSAoYyAo ' + '\n' + ' ' +
	            ' diEgKDIpICNmICNmKSkpKQ==%22))?input_0= ' + topic[word] + '"'+ '>')
			f.write(topic[word] + '</a>' + ' ' + '\n' + '\n')
		f.write('\n' + '\n')

	f.write('  ' + '</body>' + '\n')
	f.write('</html>')
	f.closed
################################################################################

# main function
def main():
	clean_file = processFile()
	clean_file = createNewFile(clean_file)
	print("Completed converting the file. Please check for file name generatedFile ")

if __name__ == "__main__": main()