# Marty Dang 5/24/18

# This program does the followering:
# 1. Takes in an input of a .txt file, as command prompt
# 2. It then scans and picks out the individual words
# 3. Outputs those words to another file
# 4. In that other file, it should append the link of the website with the word
# 5. Append all of that to a href tag for html

#Be sure to have your input text file in the same location as this program!

# Read/Open the file, outputs a list of lists 
def processFile():

	clean_file = []

	file = input("Please enter in your file: ")

	with open(file) as f:

		for read_data in f:
			read_data = read_data.split() #gets rid of spaces, tab chars etc
			clean_file.append(read_data) #Add to list 
	f.close()

	return clean_file
################################################################################

#Will create a file with just key words and link them 
def createNewFile(clean_file):

	# Adds heading stuff to html file
	f = open('Digital Ricoeur-Topic Navigator.html','w') #create another file
	f.write('<!-- Code generated by Marty Dang-->' + '\n')
	f.write('<!DOCTYPE html>' + '\n')
	f.write('<html lang=' + '"en"'+ '>' + '\n')
	f.write('<meta charset="utf-8">' + '\n' + '\n')
	f.write('  ' + '<body>' + '\n')
	f.write( '  ' + '<center><h2>Digital Ricoeur - Topic Navigator</h2></center>' + '\n' +'\n')

	# Take the first word in each line and make it the title for the topic group
	for topics in clean_file:
		f.write('  ' + '<h3>' + topics[0][1:-1] + '</h3>' + '\n' + '\n')

		# The rest is just in that group 
		for word in range(1,len(topics)):
			f.write('  ' + '<a href=' +	'"' + ' https://digitalricoeur.org/search/' + topics[word] + '"'+ '>')
			f.write(topics[word] + '</a>' + ' ' + '\n' + '\n')
		f.write('\n' + '\n')

    # Write ending stuff to html file. 
	f.write('  ' + '</body>' + '\n')
	f.write('</html>')
	f.close()

################################################################################
# main function
def main():
	clean_file = processFile()
	createNewFile(clean_file)
	print("Completed converting the file.")

if __name__ == "__main__": main()